# Generated by Django 5.0.6 on 2024-05-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Season_Ticket_Avg_Price_EUR', models.FloatField()),
                ('Avg_Attenance', models.IntegerField()),
                ('Avg_Annual_Salary_USD', models.FloatField()),
                ('Population_Millions', models.FloatField()),
            ],
        ),
    ]
