# Generated by Django 5.0.6 on 2024-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_teamdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamdata',
            old_name='Avg_Attenance',
            new_name='Avg_Attendance',
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='Avg_Annual_Salary_USD',
            field=models.IntegerField(),
        ),
    ]
