# Generated by Django 5.0.6 on 2024-06-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_avg_attenance_teamdata_avg_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='Avg_Attendance',
            field=models.FloatField(),
        ),
    ]
