# Generated by Django 5.0.6 on 2024-06-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_teamdata_avg_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='Avg_Attendance',
            field=models.IntegerField(),
        ),
    ]
