# Generated by Django 5.0.6 on 2024-06-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_userfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='Capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='Number_Spectators',
            field=models.IntegerField(default=0),
        ),
    ]
