# Generated by Django 5.0.6 on 2024-06-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_teamdata_capacity_teamdata_number_spectators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamdata',
            old_name='Number_Spectators',
            new_name='Number_of_Spectators',
        ),
    ]
