# Generated by Django 5.0.6 on 2024-06-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_number_spectators_teamdata_number_of_spectators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdata',
            name='Capacity',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='Number_of_Spectators',
        ),
    ]
