# Generated by Django 5.0.6 on 2024-06-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_teamdata_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='Capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='Number_of_Spectators',
            field=models.IntegerField(default=0),
        ),
    ]
